# This file was generated by GoReleaser. DO NOT EDIT.
cask "dtctl" do
  version "26.0.0"

  on_macos do
    on_arm do
      sha256 "3770c6f33cabc08aec851dd5892c9c987692ff7964776ca3e29ef80be9e1d4e6"
      url "https://github.com/dtcloudnow/dt-cli/releases/download/v#{version}/dtctl-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/dtcloudnow/dt-cli"
    end
    on_intel do
      sha256 "7f0bc96d6aafb17d159c3b46962bfb3e4c06ebbb88e95903476c3c36b8eea46d"
      url "https://github.com/dtcloudnow/dt-cli/releases/download/v#{version}/dtctl-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/dtcloudnow/dt-cli"
    end
  end
  on_linux do
    on_arm do
      sha256 "bde65aa1d8c77d60ab4ac8990ffd86cee32aa1de08a9dc4d2d30af642127d830"
      url "https://github.com/dtcloudnow/dt-cli/releases/download/v#{version}/dtctl-#{version}-linux-arm64.tar.gz",
        verified: "github.com/dtcloudnow/dt-cli"
    end
    on_intel do
      sha256 "79c76fffe1e72f1209d9cc2f9894efda05dfd2be413ddafaaad9612213428fd5"
      url "https://github.com/dtcloudnow/dt-cli/releases/download/v#{version}/dtctl-#{version}-linux-amd64.tar.gz",
        verified: "github.com/dtcloudnow/dt-cli"
    end
  end

  name "dtctl"
  desc "The official DT Cloud command line interface"
  homepage "https://github.com/dtcloudnow/dt-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dtctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/dtctl"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    dtctl is not notarized by Apple. If macOS still refuses to start it:
      xattr -dr com.apple.quarantine $(which dtctl)
  EOS
end
