# This file was generated by GoReleaser. DO NOT EDIT.
cask "dtctl" do
  version "1.1.0-rc.1"

  on_macos do
    on_arm do
      sha256 "74f6d835d5c5b00eeab0822bcd9d603fa700841d31ce84bb1f5dd1a3cabebc3a"
      url "https://github.com/dtcloudnow/dt-cli/releases/download/v#{version}/dtctl-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/dtcloudnow/dt-cli"
    end
    on_intel do
      sha256 "6d2f7823549534ac2efa8c07ba2d0a4720571e9f2f3e391e9b3659459b856dd1"
      url "https://github.com/dtcloudnow/dt-cli/releases/download/v#{version}/dtctl-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/dtcloudnow/dt-cli"
    end
  end
  on_linux do
    on_arm do
      sha256 "e2aa48aa6ce9ca92aeb1a321470a28551f4de6bc715c4dc737e3ba164f17069e"
      url "https://github.com/dtcloudnow/dt-cli/releases/download/v#{version}/dtctl-#{version}-linux-arm64.tar.gz",
        verified: "github.com/dtcloudnow/dt-cli"
    end
    on_intel do
      sha256 "3938dc5c7b34a6a23045ced0a8fecb8507548a08cec50e6dd7fd81017b4a9e68"
      url "https://github.com/dtcloudnow/dt-cli/releases/download/v#{version}/dtctl-#{version}-linux-amd64.tar.gz",
        verified: "github.com/dtcloudnow/dt-cli"
    end
  end

  name "dtctl"
  desc "The official DT Cloud command line interface"
  homepage "https://github.com/dtcloudnow/dt-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dtctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/dtctl"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    dtctl is not notarized by Apple. If macOS still refuses to start it:
      xattr -dr com.apple.quarantine $(which dtctl)
  EOS
end
