# This file was generated by GoReleaser. DO NOT EDIT.
cask "dtctl" do
  version "1.1.0"

  on_macos do
    on_arm do
      sha256 "934123b8672ceb8a4d0e4eb92bf608b83f8ac58daaf0c0c1cfcac84b69b3dd8e"
      url "https://github.com/dtcloudnow/dt-cli/releases/download/v#{version}/dtctl-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/dtcloudnow/dt-cli"
    end
    on_intel do
      sha256 "815962fbc96142a61d68c9ed630d5b6a075d9970dd1720bc2a154475748a9e55"
      url "https://github.com/dtcloudnow/dt-cli/releases/download/v#{version}/dtctl-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/dtcloudnow/dt-cli"
    end
  end
  on_linux do
    on_arm do
      sha256 "651728cd57c11f97325466cf51777194d7e736c6c1c4de737f6ed52d45525fc5"
      url "https://github.com/dtcloudnow/dt-cli/releases/download/v#{version}/dtctl-#{version}-linux-arm64.tar.gz",
        verified: "github.com/dtcloudnow/dt-cli"
    end
    on_intel do
      sha256 "ef5fcc66f804547de33a8c93a7a5ce79b223c6e57098eef459e4bba558e8aef6"
      url "https://github.com/dtcloudnow/dt-cli/releases/download/v#{version}/dtctl-#{version}-linux-amd64.tar.gz",
        verified: "github.com/dtcloudnow/dt-cli"
    end
  end

  name "dtctl"
  desc "The official DT Cloud command line interface"
  homepage "https://github.com/dtcloudnow/dt-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dtctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/dtctl"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    dtctl is not notarized by Apple. If macOS still refuses to start it:
      xattr -dr com.apple.quarantine $(which dtctl)
  EOS
end
